### PR TITLE
fix New credential is added the bottom of credential section

### LINKED ISSUE #9059: Stack-Editor: New credential is added the bottom of credential section
When user create new credential, it is added to bottom of credentials section.
We want to see this new credential at the top of this section.

After refreshing the browser credentials are sorted right.

## Expected Behavior
When user add new credential, it should be added to top of credentials section in stack-editor page.

## Current Behavior
New credential is added to bottom of credential section.

## Possible Solution
Check computeController's `CredentialAdded` event

## Steps to Reproduce (for bugs)
1. Go to credentials page in stack-editor
2. Create new credential
3. it is added to bottom of this section

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37968508-stack-editor-new-credential-is-added-the-bottom-of-credential-section?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ezgikaysi**
## Description

When user create new credential, it is added to bottom of credentials section.
We want to see this new credential at the top of this section.
## Motivation and Context

fixes: #9059 
## How Has This Been Tested?

Manually
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: client/app/lib/views/credentiallist/accountcredentiallistcontroller.coffee [hunk 1]
```diff
@@ -301,6 +301,7 @@ module.exports = class AccountCredentialListController extends KodingListControl
       then @addItem(credential).verifyCredential()
       else
         @addItem credential
+        @loadItems()
```
Comment (hakankaradis) [inline client/app/lib/views/credentiallist/accountcredentiallistcontroller.coffee]: No need to call super class after adding a new credential.
Better to give index as a second argument to addItem function.
https://github.com/koding/kd/blob/master/lib/components/list/listviewcontroller.coffee#L168
`@addItem credential, 0` would add item to top
/cc: @sinan

Comment (ezgikaysi) [inline client/app/lib/views/credentiallist/accountcredentiallistcontroller.coffee]: I changed loaditem function to addItem function

**Review by hakankaradis — APPROVED** [review]

**Comment by hakankaradis** [comment]
👍
