### PR TITLE
Improve/fix disabled user stack functionalities

### LINKED ISSUE #10928: Disabled user stacks are listed on dashboard after reloading the page.
## Current Behavior
gif
http://recordit.co/irJXXt5U6P

They disappear again after closing and reopening the dashboard.
But appearing if you view the disabled user's machine on virtual machines tab.

### LINKED ISSUE #11023: New team default stack is added to a member's sidebar directly.
## Current Behavior
gif
http://recordit.co/SD1YLchVmZ

### LINKED ISSUE #11045: Disabled user's stack cannot be accessed.
## Current Behavior
gif
http://recordit.co/RLDwstAIve

### PR DESCRIPTION
**Pull request by usirin**
Fixes #10928 
Fixes #11023 
Fixes #11045 

@gokmen there is a problem while trying to call `machine.kite.getInfo` when we try to load a disabled user's machine.

### CODE REVIEW

File: client/app/lib/remote-extensions/machine.coffee [hunk 1]
```diff
@@ -60,14 +60,6 @@ module.exports = class JMachine extends remote.api.JMachine
...
         require('../util/fs/fsitem').create options, callback
 
-    @on 'update', =>
-
-      { reactor } = kd.singletons
-      actions     = require 'app/flux/environment/actiontypes'
-      reactor.dispatch actions.MACHINE_UPDATED, {
-        id: @_id, machine: this
-      }
-
```
Comment (gokmen) [inline client/app/lib/remote-extensions/machine.coffee]: why did you remove? This was handling machine turn on/off state changes afair.

File: client/app/lib/providers/computecontroller.coffee [hunk 2]
```diff
@@ -862,6 +862,7 @@ module.exports = class ComputeController extends KDController
     existents = 0
     for stackTemplateId in stackTemplates
       existentStacks = @storage.stacks.query 'baseStackId', stackTemplateId
+      existentStacks = existentStacks.filter (stack) -> not stack.getOldOwner()
```
Comment (gokmen) [inline client/app/lib/providers/computecontroller.coffee]: 👍

File: client/app/lib/remote-extensions/machine.coffee [hunk 3]
```diff
@@ -286,9 +278,9 @@ module.exports = class JMachine extends remote.api.JMachine
     { Own, Shared, Reassigned, Collaboration } = JMachine.Type
 
     switch
-      when @isMine()      then Own
       when @isPermanent() then Shared
       when @getOldOwner() then Reassigned
+      when @isMine()      then Own
```
Comment (gokmen) [inline client/app/lib/remote-extensions/machine.coffee]: does `isMine` not working correctly for disabled stacks? if so, it might be better to handle/fix it in there.

**Review by gokmen — COMMENTED** [review]
it looks good to me, but there are some points that I commented on. Let's have a session on these.

**Review by gokmen — APPROVED** [review]
