### PR TITLE
prefetch: fix git check

### LINKED ISSUE #11048: kd/mount: initial prefetch fails with exit status 23
Initial prefetch fails with:

```
Cannot prefetch mount files: file prefetching interrupted (exit status 23)
```
```
$ kd mount lime_grape
Mounting to /Users/rjeczalik/koding/mnt/aws-instance-2 directory.
Checking remote path...
Mounted remote directory /home/rjeczalik has 10 file(s) of total size 132 KiB
Initializing mount /home/rjeczalik -> /Users/rjeczalik/koding/mnt/aws-instance-2...
Using git files strategy to prefetch initial mount data.
Copying files: NaN% (0/1), 0 B/0 B | 0 B/s
Cannot prefetch mount files: file prefetching interrupted (exit status 23)
Created mount with ID: 82938d8b-ecd0-43c5-a08f-c63d49851266
```

Bonus

Fix formatting:

```
Copying files: NaN% (0/1), 0 B/0 B | 0 B/s
```

### PR DESCRIPTION
**Pull request by rjeczalik**
Fixes #11048.

### CODE REVIEW

File: go/src/koding/klient/machine/mount/prefetch/git.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func (Git) Scan(idx *index.Index) (string, int64, int64, error) {
 		return !n.IsShadowed()
 	})
 
-	if isGit {
+	if !isGit {
```
Comment (ppknap) [inline go/src/koding/klient/machine/mount/prefetch/git.go]: 🤦‍♂️

**Review by ppknap — APPROVED** [review]
