### PR TITLE
client: update for vms' details

### LINKED ISSUE #9173: Incorrect Amount of RAM and CPUs Displayed in VM Details
## Current Behavior

Incorrect amount of ram and CPUs are displayed in the VM details of the dashboard section

An M4.2xl shows 1GB of RAM and 1xCPU:
image
## Steps to Reproduce (for bugs)

Go to the Dashboard and open the details of a VM.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38010724-incorrect-amount-of-ram-and-cpus-displayed-in-vm-details?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cansirin**
## Description

Currently, VM's CPU and RAM weren't displayed correctly. This PR updates that information.
## Motivation and Context

Fixes #9173 
## How Has This Been Tested?

Manually
## Screenshots (if appropriate):

image
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee [hunk 1]
```diff
@@ -225,8 +225,15 @@ generateSpecs = (machine) ->
...
+    'm4.large'  : '8GB RAM'
+    'm4.xlarge' : '16GB RAM'
+    'm4.2xlarge': '32GB RAM'
   }[type] ? '1GB RAM'
-  specs.push cpu = '1x CPU'
+  specs.push cpu = {
+    'm4.large'   : '2x CPU'
+    'm4.xlarge'  : '4x CPU'
+    'm4.2xlarge' : '8X CPU'
+  }[type] ? '1x CPU'
```
Comment (usirin) [inline client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee]: @gokmen is there a dynamic way that we can get this list?

Comment (gokmen) [inline client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee]: not currently and this existing list also needed to be provider specific, these are only valid for `aws` provider only. I suggest to create a provider specific list somewhere else and not keep all these information in the view.

**Review by usirin — APPROVED** [review]

**Comment by hakankaradis** [comment]
@cansirin needs rebase

File: client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee [hunk 2]
```diff
@@ -217,16 +218,17 @@ generateSpecs = (machine) ->
 
   specs = []
 
+  providerName = jMachine.meta?.type
+  instanceType = jMachine.meta?.instance_type ? 't2.micro'
   size = jMachine.meta?.storage_size
 
+  { ram } = providerSpecs[providerName][instanceType]
+  { cpu } = providerSpecs[providerName][instanceType]
```
Comment (gokmen) [inline client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee]: this will fail if vm has different provider like `vagrant` there needs to be defaults for each spec.

File: client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee [hunk 3]
```diff
@@ -217,16 +218,17 @@ generateSpecs = (machine) ->
 
   specs = []
 
+  providerName = jMachine.meta?.type
+  instanceType = jMachine.meta?.instance_type ? 't2.micro'
```
Comment (gokmen) [inline client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee]: `t2.micro` shouldn't be default here, it can be `base-vm` something cc/ @sinan

File: client/app/lib/constants/providerSpecs.coffee [hunk 4]
```diff
@@ -0,0 +1,20 @@
+module.exports =
```
Comment (gokmen) [inline client/app/lib/constants/providerSpecs.coffee]: let's make this a method takes `provider` as a parameter and returns list of available types

**Review by gokmen — CHANGES_REQUESTED** [review]

File: client/app/lib/constants/providerSpecs.coffee (hunk 4 above)
Comment (usirin) [inline client/app/lib/constants/providerSpecs.coffee]: 👍 So @cansirin we need to move this file under `client/app/lib/util`, make it a function that accepts a `provider` argument, and return the list depending on this `provider` argument. And rename it to `makeProviderStacks.coffee`

File: client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee (hunk 2 above)
Comment (usirin) [inline client/home/lib/virtualmachines/components/machineslist/machinedetails.coffee]: @rjeczalik Can you please direct us to the correct place where we can find the implemented `provider`s and their specs? Especially i am interested in to see what the defaults are for each provider, so that we can have that info and show those to the users correctly.

**Comment by cansirin** [comment]
updated. /cc @gokmen

**Review by gokmen — APPROVED** [review]

**Comment by gokmen** [comment]
LGTM 👍 but let's wait for this one for deploy and/or for #9319
