### PR TITLE
Resource state modal: bug fixes and improvements

### LINKED ISSUE #8875: Resource state modal: left button in footer is broken in Safari
## Expected Behavior
Button should have correct width

## Current Behavior
Button is too wide
http://take.ms/CoUTc

### PR DESCRIPTION
**Pull request by alex-ionochkin**
## Description

This PR fixes https://github.com/koding/koding/issues/8875 and https://github.com/koding/koding/issues/8860. Also, it implements https://github.com/koding/koding/issues/8876
## Screenshots (if appropriate):

http://take.ms/gyFbu (Safari)
http://recordit.co/zYFjfmCrlb

### CODE REVIEW

File: client/app/lib/components/codeblock/index.coffee [hunk 1]
```diff
@@ -3,6 +3,7 @@ React = require 'kd-react'
 globals = require 'globals'
 Tracker = require 'app/util/tracker'
 copyToClipboard = require 'app/util/copyToClipboard'
+getCopyToClipboardShortcut = require 'app/util/getCopyToClipboardShortcut'
```
Comment (sinan) [inline client/app/lib/components/codeblock/index.coffee]: 👍

**Comment by sinan** [comment]
also can you please make a sitewide search to check if that util has to be used on older parts?
