### PR TITLE
Tooltip for the 'Credentials' tab is not working consistently.

### LINKED ISSUE #8602: Tooltip for the 'Credentials' tab is not working consistently.
_When you try to save a stack template without selecting any credentials:_
gif
http://recordit.co/BKZKAzJCYh

_When you select a valid credential after trying to use an invalid credential twice:_
gif
http://recordit.co/ImDylSYKhY

### PR DESCRIPTION
**Pull request by hakankaradis**
fixes #8602 
http://recordit.co/rMYL5EqTl5

### CODE REVIEW

File: client/stack-editor/lib/editor/index.coffee [hunk 1]
```diff
@@ -396,11 +396,16 @@ module.exports = class StackEditorView extends kd.View
 
           if err
             @credentialWarning.once 'transitionend', =>
+              if @credentialWarning.getAttribute('class').indexOf(' in') > 0
```
Comment (sinan) [inline client/stack-editor/lib/editor/index.coffee]: `@credentialWarning.getElement().classList.contains 'in'`

Comment (sinan) [inline client/stack-editor/lib/editor/index.coffee]: Or even `@credentialWarning.hasClass 'in'`

Comment (hakankaradis) [inline client/stack-editor/lib/editor/index.coffee]: @sinan updated
