### PR TITLE
klient: rework klient/client tests - fixes #9129

### LINKED ISSUE #9129: klient: a race in tests
There are a number of races in klient tests ([that still require fixing](https://github.com/koding/koding/blob/master/scripts/test-klient.sh#L5)), the one that is fairly often reproducible and is a reason for a frequent build failures:

```
016-09-27 14:10:29 [testing] INFO     client.Publish: Publishing data for event 'test'
fatal error: concurrent map writes

goroutine 96 [running]:
runtime.throw(0x828cfa, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42005bd50 sp=0xc42005bd30
runtime.mapassign1(0x7b3980, 0xc42041e2a0, 0xc42005be68, 0xc42005be5f)
	/usr/local/go/src/runtime/hashmap.go:553 +0x2e1 fp=0xc42005be38 sp=0xc42005bd50
koding/klient/client.TestUnsubscribe.func1(0xc42023e510)
	/pipeline/build/go/src/koding/klient/client/client_test.go:331 +0x70 fp=0xc42005be88 sp=0xc42005be38
vendor/github.com/koding/kite.(*Client).runCallback(0xc4202aac00, 0xc420268200, 0xc42023e510)
	/pipeline/build/go/src/vendor/github.com/koding/kite/request.go:127 +0x56 fp=0xc42005beb0 sp=0xc42005be88
vendor/github.com/koding/kite.(*Client).readLoop(0xc4202aac00, 0x0, 0x0)
	/pipeline/build/go/src/vendor/github.com/koding/kite/client.go:388 +0x1cd fp=0xc42005bf38 sp=0xc42005beb0
vendor/github.com/koding/kite.(*Client).run(0xc4202aac00)
	/pipeline/build/go/src/vendor/github.com/koding/kite/client.go:327 +0x2f fp=0xc42005bf98 sp=0xc42005bf38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42005bfa0 sp=0xc42005bf98
created by vendor/github.com/koding/kite.(*Client).DialTimeout
	/pipeline/build/go/src/vendor/github.com/koding/kite/client.go:202 +0x163
```

Would be good to also enable -race for kd tests - https://github.com/koding/koding/issues/9128.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38001610-klient-a-race-in-tests?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41989991&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ppknap**
This PR fixes all klient/client data races in tests.
## Motivation and Context

These changes should remove frequent "klient/client" false negative test results from our CI. This fixes #9129.
## How Has This Been Tested?

Manually, running improved unit tests.
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: go/src/koding/klient/client/client.go [hunk 1]
```diff
@@ -120,16 +119,11 @@ func (c *PubSub) Publish(r *kite.Request) (interface{}, error) {
 	// all of the subs manually. If it doesn't, something wrong occured
 	// during the removal attempt.
 	if len(subs) == 0 {
-		c.Log.Info(fmt.Sprintf(
-			"client.Publish: The event '%s' was found empty, when it should "+
-				"have  been removed\n", params.EventName))
-		return nil, errors.New(fmt.Sprintf(
-			"client.Publish: No client.Subscribers found for '%s'",
-			params.EventName))
+		c.Log.Info("client.Publish: The event '%s' was found empty, when it should have  been removed\n", params.EventName)
```
Comment (rjeczalik) [inline go/src/koding/klient/client/client.go]: if you spot '%s' replace it with %q

File: go/src/koding/klient/client/client_test.go [hunk 2]
```diff
@@ -88,13 +143,14 @@ func TestSubscribe(t *testing.T) {
 	if err != nil {
 		t.Error(err)
 	}
+	wait(t, doneC, time.Second)
 
-	_, ok := ps.Subscriptions["test"]
+	subs, ok := getCopy(ps, "test")
```
Comment (rjeczalik) [inline go/src/koding/klient/client/client_test.go]: you can remove second bool return value here, return nil map if it's not found and test for len(subs) as you do at L187

**Review by rjeczalik — APPROVED** [review]

File: go/src/koding/klient/client/client_test.go (hunk 2 above)
Comment (ppknap) [inline go/src/koding/klient/client/client_test.go]: done

File: go/src/koding/klient/client/client_test.go [hunk 3]
```diff
@@ -19,12 +19,63 @@ func (f mockCaller) Call(v ...interface{}) error {
...
+		}
+
+		return result, err
+	})
+}
+
+// wait is a helper function that waits for an event from done channel or
+// timeouts after specified timeout. This function must be called from main
+// go-routine only.
+func wait(t *testing.T, doneC <-chan struct{}, timeout time.Duration) {
```
Comment (cihangir) [inline go/src/koding/klient/client/client_test.go]: since you dont call this within a goroutine, you could Fail with t, instead of panicing.

Comment (ppknap) [inline go/src/koding/klient/client/client_test.go]: yes I can. However, If I fail here, I will get only the line number where t.Fatal was called(always the same), and will not know the line where actually test fails. `panic` solves this since it prints stack trace.

Comment (rjeczalik) [inline go/src/koding/klient/client/client_test.go]: Can't we just return error here instead and call t.Fatal outside this func?

```go
func wait(doneC <-chan struct{}, timeout time.Duration) error {
	select {
 	case <-doneC:
 	 	return nil
 	case <-time.After(timeout):
 	 	return fmt.Errorf("timed out after %s", timeout)
 	}
 }

if err := wait(c, 2 * time.Second); err != nil {
    t.Fatal(err)
} 
```

Comment (ppknap) [inline go/src/koding/klient/client/client_test.go]: Let it be (despite of the fact that this will add ~50-60 lines to this test). I will send new PR for this to not pollute this one.

Comment (rjeczalik) [inline go/src/koding/klient/client/client_test.go]: > this will add ~50-60 lines to this test

Don't bother, we have a lot of lines, can throw more if needed 😎 

pic

Comment (ppknap) [inline go/src/koding/klient/client/client_test.go]: Changes here: #9152
