### PR TITLE
deployment/nginx: on proxy machines check health of tunnelserver as w…

### LINKED ISSUE #9742: Vagrant credential verify failed with 'operation timed out' error.
## Current Behavior
partial `kd log` output:
```
2016-11-24T16:56:42.607Z CRITICAL [tunnelclient   ][PID:37158][logging/context.go:23] [transport] client fetch identifier error: dial failed: dial tcp 52.49.64.184:80: getsockopt: connection refused
2016-11-24T16:57:32.161Z CRITICAL [tunnelclient   ][PID:37158][logging/context.go:23] [transport] client fetch identifier error: dial failed: dial tcp 52.49.64.184:80: getsockopt: connection refused
2016-11-24 18:58:15 [klient] INFO     Kite 'unknown/production/kd' is connected
2016-11-24 18:58:15 [klient] INFO     Kite 'maryjane/production/kd' called method: 'remote.list'
2016-11-24 18:58:15 [klient] INFO     Kite 'maryjane/production/kd' is disconnected
2016-11-24 18:58:15 [klient] INFO     Start disconnection timer with 1 minute delay.
2016-11-24T16:58:31.449Z CRITICAL [tunnelclient   ][PID:37158][logging/context.go:23] [transport] client fetch identifier error: dial failed: dial tcp 52.208.156.227:80: getsockopt: connection refused
2016-11-24 18:59:15 [klient] INFO     Unsharing users 'map[maryjane:%!!(MISSING)s(*collaboration.Option=&{true }) veronicamars:%!!(MISSING)s(*collaboration.Option=&{true })]'
2016-11-24 18:59:15 [klient] INFO     User is permanent, avoiding it: "veronicamars"
2016-11-24 18:59:15 [klient] INFO     User is permanent, avoiding it: "maryjane"
2016-11-24T16:59:18.996Z CRITICAL [tunnelclient   ][PID:37158][logging/context.go:23] [transport] client fetch identifier error: dial failed: dial tcp 52.49.64.184:80: getsockopt: connection refused
2016-11-24T17:00:07.386Z CRITICAL [tunnelclient   ][PID:37158][logging/context.go:23] [transport] client fetch identifier error: dial failed: dial tcp 52.208.156.227:80: getsockopt: connection refused
```

### PR DESCRIPTION
**Pull request by cihangir**
fixes #9742 

Operational changes has been implemented, this change will make sure any kind of future failures to fix themselves

### CODE REVIEW

**Review by rjeczalik — APPROVED** [review]

File: deployment/nginx.coffee [hunk 1]
```diff
@@ -441,12 +441,25 @@ createHealthcheck = (KONFIG) ->
...
-      listen 78;
+        listen 78;
 
-      location = /healthcheck {
-        return 200;
-        access_log off;
-      }
+        # proxy healthcheck requests to tunnelserver, if nginx is down,
+        # healthcheck does its job, if tunnelserver is down, healthcheck again
+        # does its job, two bird, one stone
```
Comment (gokmen) [inline deployment/nginx.coffee]: 👍

**Comment by szkl** [comment]
👍
