### PR TITLE
provider/google: user specified data is not executed during machine bootstrap. Fixes #9540

### LINKED ISSUE #9540: user-data is not working on Google Cloud stacks.
Example template:
```provider:
  google:
    credentials: '${var.google_credentials}'
    project: '${var.google_project}'
    region: '${var.google_region}'

resource:
  google_compute_instance:
    # this is the name of your VM
    google-instance:
      # and this is its identifier (required)
      name: google-instance
      # select your instance_type here: eg. n1-standard-1
      machine_type: f1-micro
      # base image for your instance
      disk:
        image: ubuntu-1404-lts
      # select your instance zone which must be in provided region: eg. us-central1-a
      zone: us-central1-a
      metadata:
        # on user_data section we will write bash and configure our VM
        user-data: |-
          # let's create a file on your root folder:
          echo "hello world!" >> /helloworld.txt
```

### PR DESCRIPTION
**Pull request by ppknap**
## Description
Metadata is stored as an array of `map[string]interface{}` objects. Because of this, previous type assertion didn't work. Now, we flatten this array to single `map[string]interface{}` instance.

## Motivation and Context
Bug fix.

## How Has This Been Tested?
Manually

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: go/src/koding/kites/kloud/provider/google/stack.go [hunk 1]
```diff
@@ -359,6 +359,23 @@ func (s *Stack) getDiskSize(currentProject string, computeService *compute.Servi
...
 
+func flatten(data []map[string]interface{}) map[string]interface{} {
+	res := make(map[string]interface{})
+	for _, ms := range data {
+		for key, m := range ms {
+			if val, ok := m.(string); ok {
+				if res[key] == nil {
+					res[key] = val
+				} else {
+					res[key] = res[key].(string) + "\n" + val
```
Comment (rjeczalik) [inline go/src/koding/kites/kloud/provider/google/stack.go]: Why do you merge with newline? Is it possible to specify in terraform template the same key multiple times with different values?

File: go/src/koding/kites/kloud/provider/google/stack.go [hunk 2]
```diff
@@ -359,6 +359,23 @@ func (s *Stack) getDiskSize(currentProject string, computeService *compute.Servi
 	}
 }
 
+func flatten(data []map[string]interface{}) map[string]interface{} {
```
Comment (cihangir) [inline go/src/koding/kites/kloud/provider/google/stack.go]: Could you write test for flatten?

Comment (ppknap) [inline go/src/koding/kites/kloud/provider/google/stack.go]: sure, sir!

Comment (ppknap) [inline go/src/koding/kites/kloud/provider/google/stack.go]: done

**Review by rjeczalik — APPROVED** [review]

**Comment by rjeczalik** [comment]
@cihangir Test added. Merging for now. If another pass is needed -> comment -> next PR. (cc @ppknap).

**Comment by cihangir** [comment]
LGTM, thanks!
