### PR TITLE
kd/mount: fix performance problems when accessing large git repositories

### LINKED ISSUE #11064: kd/mount: check performance problems when accessing large git repositories
Apparently, git index algorithm detects file attributes set by mounts as not consistent with these stored in .git/index file. This causes git to read all files inside repository and compute SHA-1 sum for each of the files.

The goal of this issue is to make git diff detection algorithm happy with file attributes set by mounts. Some reading about which file attributes git index checks is [here](https://www.kernel.org/pub/software/scm/git/docs/technical/racy-git.txt) 

## Expected Behavior
Git doesn't have to compute SHA-1 sum of each file in mounted repository.

## Current Behavior
It does.

## Possible Solution
Add/modify inode attributes to match these stored in git.

## Steps to Reproduce (for bugs)
Mount git repository, access and run `git status`.

### PR DESCRIPTION
**Pull request by ppknap**
Fixes: #11064, #11124, also it will likely fix problems with disappearing files on remote.

Note, that this will still require initial SHA-1 computation. I'm going to solve this with #11135 by introducing a function which will run `git status` on each git repository inside cache - this will set index to proper state.

## How Has This Been Tested?
Manually

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: go/src/koding/klient/machine/index/node/entry_unix.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// +build darwin dragonfly freebsd linux nacl netbsd openbsd solaris
```
Comment (cihangir) [inline go/src/koding/klient/machine/index/node/entry_unix.go]: go need `unix`type :)

**Review by cihangir — APPROVED** [review]

File: go/src/koding/klient/machine/index/node/entry_unix.go (hunk 1 above)
Comment (rjeczalik) [inline go/src/koding/klient/machine/index/node/entry_unix.go]: usually !windows works ok

Comment (rjeczalik) [inline go/src/koding/klient/machine/index/node/entry_unix.go]: https://golang.org/src/os/types_unix.go

File: go/src/koding/klient/machine/index/node/entry.go [hunk 2]
```diff
@@ -67,16 +67,16 @@ func (ep *EntryPromise) Swap(set, unset EntryPromise) {
...
 type File struct {
-	CTime int64       `json:"c"` // Metadata change time since EPOCH.
-	MTime int64       `json:"m"` // File data change time since EPOCH.
-	Size  int64       `json:"s"` // Size of the file.
-	Mode  os.FileMode `json:"o"` // File mode and permission bits.
+	CTime int64       `json:"c"`           // Metadata change time since EPOCH.
+	MTime int64       `json:"m"`           // File data change time since EPOCH.
+	Size  int64       `json:"s"`           // Size of the file.
+	Mode  os.FileMode `json:"o"`           // File mode and permission bits.
+	Inode uint64      `json:"i,omitempty"` // Inode ID of a mounted file.
```
Comment (rjeczalik) [inline go/src/koding/klient/machine/index/node/entry.go]: I see the `wip` tag, but since we started reviewing I just wanted to mention we'd need some compat code for old mounts - https://asciinema.org/a/a0v2txto44hca6wk7ixjpke04.

Comment (cihangir) [inline go/src/koding/klient/machine/index/node/entry.go]: i saw wip after reviewing - sorry for the confusion.

Comment (rjeczalik) [inline go/src/koding/klient/machine/index/node/entry.go]: I'm not complaining, just giving heads up since the changes in this PR are substantial. 😇

File: go/src/koding/klient/machine/index/node/entry_unix.go (hunk 1 above)
Comment (ppknap) [inline go/src/koding/klient/machine/index/node/entry_unix.go]: still, go needs `unix` type: https://golang.org/src/os/path_unix.go :)

File: go/src/koding/klient/machine/index/node/entry.go (hunk 2 above)
Comment (ppknap) [inline go/src/koding/klient/machine/index/node/entry.go]: yep, that's why it's wip. I didn't test this on kd mount - only loopfuse.

File: go/src/koding/klientctl/endpoint/machine/mount.go [hunk 3]
```diff
@@ -138,6 +137,15 @@ func (c *Client) Mount(options *MountOptions) (err error) {
 		}
 	}
 
+	// Rescan cache folder in order to update index.
+	upIdxMountReq := &machinegroup.UpdateIndexRequest{
+		MountID: addMountRes.MountID,
+	}
+	var upIdxMountRes machinegroup.UpdateIndexResponse
+	if err := c.klient().Call("machine.mount.updateIndex", upIdxMountReq, &upIdxMountRes); err != nil {
```
Comment (rjeczalik) [inline go/src/koding/klientctl/endpoint/machine/mount.go]: 🏁

**Review by rjeczalik — APPROVED** [review]

File: go/src/koding/klientctl/endpoint/machine/mount.go (hunk 3 above)
Comment (szkl) [inline go/src/koding/klientctl/endpoint/machine/mount.go]: @rjeczalik that's my 🏁 flag. Here's yours 🚩

Comment (rjeczalik) [inline go/src/koding/klientctl/endpoint/machine/mount.go]: Oh, I'm always late to the party. 🏴

**Review by cihangir — APPROVED** [review]
