### PR TITLE
load improvements -- more fixes

### LINKED ISSUE #10878: Default stack is listed under 'Private Stacks' section for the owner until reloading the page.
## Current Behavior
gif
http://recordit.co/MZhnFR23hQ

### LINKED ISSUE #10886: Private stack shared with the team is displayed as unshared until reloading the page.
## Current Behavior
gif
http://recordit.co/cgPYBlniEA

Therefore 'Share With Team' option is still available on the sidebar.

Note:This happens only for the owner of the stack.

### LINKED ISSUE #10887: Disabled user's machine and modal for fixing permissions are displayed after reloading the page.
## Current Behavior
gif
http://recordit.co/H27NNAmiLb

### LINKED ISSUE #10889: 'VM Sharing' is displayed as disabled whenever the dashboard is opened again.
## Current Behavior
gif
http://recordit.co/cg421pVvWN

Reopening or reloading doesn't fix the problem.

### PR DESCRIPTION
**Pull request by usirin**
- [x] fixes #10878 
- [x] fixes #10886
- [x] fixes #10887
- [x] fixes #10889

### CODE REVIEW

**Comment by usirin** [comment]
@gokmen can we talk about #10878 and #10886

File: client/app/lib/components/sidebarstacksection/index.coffee [hunk 1]
```diff
@@ -150,48 +150,63 @@ module.exports = class SidebarStackSection extends React.Component
...
 
-    { originId, accessLevel } = template.toJS()  if template
+    { template, stack } = @props
+    { storage } = kd.singletons.computeController
+
+    template = template.toJS()
+    stack = stack.toJS()
+    account = whoami()
+
+    isMyTemplate = template?.originId is account._id
```
Comment (gokmen) [inline client/app/lib/components/sidebarstacksection/index.coffee]: we can use `template.isMine()` here but probably you need to use `remote.revive` for that, just saying.

**Review by gokmen — APPROVED** [review]
