### PR TITLE
Fix Some Release Bugs

### LINKED ISSUE #9941: 'Terminate' button should be updated as 'Log Out'
## Current Behavior
image

And the modal appearing after clicking on it:
image

Question here should be updated as 'Do you really want to log out from [Team Name]?'

### PR DESCRIPTION
**Pull request by hakankaradis**
Fixes: #9941, #9945, #9949, #9953, #9979, #9980, #9976 

- Members will not be allowed to clone stack when stack creation is disabled.
- Fix some button styles in `are you sure?` modals
- minor copy changes
- Edit name in stack editor section is clickable when the other tabs active
- Style fix for text box next to `Syntax` option in IDE menu items

### CODE REVIEW

File: client/app/lib/activity/sidebar/sidebarmachinesharepopup.coffee [hunk 1]
```diff
@@ -238,5 +238,5 @@ module.exports = class SidebarMachineSharePopup extends KDModalView
 
   TITLES =
     'shared machine' : 'wants to share their VM with you. <span class="footnote">* Rejecting this will destroy any existing collaboration sessions with this machine.</span>'
-    'collaboration'  : 'wants to collaborate with you on their VM.'
+    'collaboration'  : 'wants to collaborate on with you on their VM.'
```
Comment (sinan) [inline client/app/lib/activity/sidebar/sidebarmachinesharepopup.coffee]: that's correct copy, the one you need to change is not this one. Apply this `wants to collaborate with you on their VM.` to this https://github.com/koding/koding/issues/9980

**Review by sinan — CHANGES_REQUESTED** [review]
one minor change.
