### PR TITLE
ide/drawing: fix drawing pane error

### LINKED ISSUE #9523: 'Drawing Board' feature is broken.
## Current Behavior
gif
http://recordit.co/VW66sy7qmT

### PR DESCRIPTION
**Pull request by hakankaradis**
fixed #9523 
Somehow @$canvas.getDomElement() wasn't returning the correct dom element.
Add cssClass attribute and used jquery to find dom element.

http://recordit.co/nNKIkuVHFE

### CODE REVIEW

File: client/ide/lib/workspace/panes/idedrawingpane.coffee [hunk 1]
```diff
@@ -110,12 +111,12 @@ module.exports = class IDEDrawingPane extends IDEPane
 
   init: ->
 
-    @$canvas = @canvas.getDomElement()
+    @$canvas = $('canvas.drawing')
```
Comment (gokmen) [inline client/ide/lib/workspace/panes/idedrawingpane.coffee]: this is not a correct solution, but let's merge this one for now. we need to revert this later. this selector looks dangerous to me.

**Review by gokmen — APPROVED** [review]
