### PR TITLE
kd: rework bolt handling

### LINKED ISSUE #11154: kd: is not able to run concurrently with other long-running processes
## Steps to reproduce
[asciicast](https://asciinema.org/a/8l0nhlxb8y94tf54wch62fxy1)

### Signature
```
2f726a65637a616c696b2f31336430303064382d663136612d343330312d613936332d3334626134636364336636342f6275672f663537383438613334356537646664373039386662336263623932363430656236316363363762632e6a736f6e2e677a2e30
```

### PR DESCRIPTION
**Pull request by rjeczalik**
Closes  #11154.

This PR reworks bolt handling in kd so it's possible to run short-running kd process alongside a long-running one:

[screencast](https://asciinema.org/a/amywiu289157qp871qf380p5s)

This PR also makes failure to obtain a bolt access a hard failure, instead of a silent one, so instead of unreadable errors kd will display:

```
$ kd mount ls
It seems that another kd process is currently running and doing write
operations that prevented me from starting up.

Usually it is enough to retry. If that happens again, please verify
you have no hanging kd processes. Alternatively if you are executing
a lot of kd processes concurrently and a number of them are failing,
you may want to increate lock timeout with:

	kd config lockTimeout 10s

error opening: timeout
$ echo $?
3
```

### CODE REVIEW

File: go/src/koding/klient/storage/storage.go [hunk 1]
```diff
@@ -104,6 +104,17 @@ func (s *Storage) DeleteValue(r *kite.Request) (interface{}, error) {
 	return true, nil
 }
 
+type ErrStorage struct {
```
Comment (cihangir) [inline go/src/koding/klient/storage/storage.go]: 👌

File: go/src/koding/klientctl/main.go [hunk 2]
```diff
@@ -129,6 +129,25 @@ func run(args []string) {
 		os.Exit(1)
 	}
 
+	cache, err := config.Open()
+	if err != nil {
+		fmt.Fprintf(os.Stderr, `It seems that another kd process is currently running and doing write
```
Comment (cihangir) [inline go/src/koding/klientctl/main.go]: 💯

**Review by cihangir — APPROVED** [review]

File: go/src/koding/klient/storage/bolt.go [hunk 3]
```diff
@@ -30,14 +30,16 @@ func NewBoltStorageBucket(db *bolt.DB, bucketName []byte) (*boltdb, error) {
...
-		_, err := tx.CreateBucketIfNotExists(b.bucket())
-		if err != nil {
-			return err
+	if !db.IsReadOnly() {
+		if err := b.Update(func(tx *bolt.Tx) error {
+			_, err := tx.CreateBucketIfNotExists(b.bucket())
+			if err != nil {
+				return err
+			}
+			return nil
```
Comment (ppknap) [inline go/src/koding/klient/storage/bolt.go]: no need for `if`, just `return err`

**Review by ppknap — APPROVED** [review]
