### PR TITLE
socialapi/emailer: fix invitations are not being send

### LINKED ISSUE #10145: Invitation emails are not sent.

### LINKED ISSUE #10146: Copy change on 'do not warn' modal for shared stack template
## Current Behavior
image

Correct copy _may be:_ 'After clicking yes, you will not receive updates for this stack anymore.'

### PR DESCRIPTION
**Pull request by cihangir**
if the user not found in the db do not error out, this might be an invitation

## Description
fixes https://github.com/koding/koding/issues/10145
fixes https://github.com/koding/koding/issues/10146
## Motivation and Context
bug fix

## How Has This Been Tested?
unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: go/src/socialapi/workers/email/emailsender/emailsender.go [hunk 1]
```diff
@@ -63,46 +61,35 @@ func (c *Controller) Process(m *Mail) error {
...
 
-	user, err := c.getUserInfo(m)
-	if err != nil {
-		if err == mgo.ErrNotFound {
-			c.log.Error("could not determine the user info for %+v, skipping this event", m)
-			return nil
-		}
-		return err
-	}
+	user := c.getUserInfo(m)
```
Comment (cihangir) [inline go/src/socialapi/workers/email/emailsender/emailsender.go]: cc/ @mehmetalisavas

**Review by rjeczalik — APPROVED** [review]
