### PR TITLE
Show correct amount for free credit on billing dashboard

### LINKED ISSUE #9944: payment: credits are not reflected properly on payment dashboard
## Expected Behavior
Free credit should include account balance

## Current Behavior
it does not show

## Possible Solution
add account balance in negative form to credit.

## Steps to Reproduce (for bugs)
1. add free credit to an account from cebeci
2.see if it is reflected on billing page

## Context
image

### PR DESCRIPTION
**Pull request by usirin**
It is computed from `customer.account_balance` property if it's less than `0`.

Alt text

/cc @cihangir 

Fixes #9944

### CODE REVIEW

File: client/app/lib/redux/modules/payment/customer.coffee [hunk 1]
```diff
@@ -63,12 +63,21 @@ coupon = (state) -> state.customer?.discount?.coupon
 
 email = (state) -> state.customer?.email
 
+freeCredit = (state) ->
+  # negative account balance means user has credits.
+  if state.customer?.account_balance < 0
+  # the amount is in cents, we want dollars.
+  then (state.customer.account_balance * -1) / 100
```
Comment (sinan) [inline client/app/lib/redux/modules/payment/customer.coffee]: `((state.customer.account_balance * -1) / 100).toFixed 2` just in case

**Review by sinan — APPROVED** [review]

File: client/app/lib/redux/modules/payment/customer.coffee (hunk 1 above)
Comment (usirin) [inline client/app/lib/redux/modules/payment/customer.coffee]: 👍

**Review by sinan — APPROVED** [review]
